### ISSUE TITLE
Support for specifying socket/core/thread counts.

### ISSUE THREAD

**Issue by pwood** [yuichiro-naito/bmd#2]
Do you have any feedback as to how you would approach altering bmd to support specifying CPU topology?

At the moment because bmd executes `bhyve -c 4` that results in a 4 socket, 1 core per socket VM. This is fine for most *nix guests, however some operating systems have socket limits (e.g. Windows 11).

To solve this we need to execute something like `-c cpus=4,sockets=1,cores=2,threads=2` to bhyve. I was going to create a PR to add `nsocket` as a new configuration directive, but then it would need to make assumptions about the core and thread count.

i.e. `ncpu=4,nsocket=2` would produce `-c cpus=4,sockets=2,cores=2,threads=1`
i.e. `ncpu=6,nsocket=3` would produce `-c cpus=6,sockets=3,cores=2,threads=1`
i.e. `ncpu=5,nsocket=2` would ERROR.

Would this be an acceptable approach for inclusion into bmd?

**Comment by yuichiro-naito** [comment]
CPU topology is not supported for now, but it's easy to add supporting it.
I prefer to support all features of sockets/cores/threads that bhyve can handle.
So, how about extending the `ncpu` directive to take one of `sockets`, `sockets:cores`, or `sockets:cores:threads` ?

i.e. `ncpu=2` would produce `-c cpus=2, sockets=2, cores=1, threads=1`
i.e. `ncpu=1:2` would produce `-c cpus=2, sockets=1, cores=2, threads=1`
i.e. `ncpu=2:4:2` would produce `-c cpus=16, sockets=2, cores=4, threads=2`

The number of `cpus` is calculated from `sockets`, `cores`, and `threads` by the configuration parser.
This keeps compatibility with the current configuration format and easy to implement.

**Comment by yuichiro-naito** [comment]
I implemented it to support the CPU topology feature by #3.
This feature will be included in the next release.

**Comment by pwood** [comment]
Amazing. Thank you so much. I was going to look at this today, but you've done it so quickly. 

Thank you.
